ito-naoya/donkoProject

- donkoProject/src/main/java/model/shippingAddresses/shippingAddressesUpdate/UpdateMainShippingAddress.java
メイン配送先を変更するメソッドを作成しました。確認をお願いします。
> メイン配送先更新ソッド作成

- donkoProject/src/main/java/model/shippingAddresses/shippingAddressesSelect/SelectShippingAddressList.java
配送先一覧のメソッドを作成しました。
確認をお願いします。
setMainShippingAddressがエラーになりますが、現在別ブランチでBeanのプルリク中のため、こちらがマージされれば解消する想定です。
> 配送先一覧メソッド作成

- donkoProject/src/main/java/model/shippingAddresses/shippingAddressesSelect/SelectShippingAddressDetail.java
> 配送先詳細情報メソッド作成

- donkoProject/src/main/java/model/users/usersSelect/SelectUserDetailFromUsers.java
> ユーザー情報詳細メソッド作成

- donkoProject/src/main/java/bean/CartBean.java
- donkoProject/src/main/java/classes/Item.java
- donkoProject/src/main/java/controller/customer/CartServlet.java
- donkoProject/src/main/java/controller/customer/DeleteCartServlet.java
- donkoProject/src/main/java/controller/customer/ItemDetailServlet.java
- donkoProject/src/main/java/controller/customer/PurchaseConfirmServlet.java
- donkoProject/src/main/java/model/items/itemsSelect/SelectItemDetailFromItems.java
- donkoProject/src/main/java/model/items/itemsSelect/SelectItemDetailOptionFromItems.java
- donkoProject/src/main/webapp/WEB-INF/views/customer/cart.jsp
- donkoProject/src/main/webapp/WEB-INF/views/customer/itemDetail.jsp
- donkoProject/src/main/webapp/WEB-INF/views/customer/purchaseConfirm.jsp
詳細画面で商品の色やサイズを一緒に表示するようにしました！
確認お願いお願いお願いお願いお願い
> 詳細オプション取得機能

- donkoProject/src/main/java/bean/ShippingAddressBean.java
変数名の部分が修正できていなかったので、再度確認お願いします。
> ShippingAddressBean修正

- donkoProject/src/main/java/classes/Item.java
- donkoProject/src/main/java/controller/customer/PurchaseConfirmServlet.java
- donkoProject/src/main/java/model/items/itemsUpdate/UpdateItemStockInItems.java
購入時に購入した商品の在庫数を減らす処理追加しました
確認お願いします。
> 購入時の商品在庫数更新機能

- donkoProject/src/main/java/classes/Item.java
- donkoProject/src/main/java/model/items/itemsSelect/SelectItemAllDetailFromItems.java
item_idに紐づいた1つの商品について、オプション含む全ての情報を取得するメソッドです！
かくにをおねがいします
> 商品情報取得メソッド(items,options)

- donkoProject/src/main/java/controller/user/EditUserInfoServlet.java
- donkoProject/src/main/webapp/WEB-INF/views/user/editUserInfo.jsp
> ユーザー情報編集画面作成

- donkoProject/src/main/java/controller/customer/MyPageServlet.java
- donkoProject/src/main/java/model/purchases/purchasesSelect/SelectMyPurchaseHistory.java
- donkoProject/src/main/java/model/shippingAddresses/shippingAddressesInsert/InsertNewShippingAddress.java
> クラス・メソッド修正

- donkoProject/src/main/java/classes/Item.java
- donkoProject/src/main/java/classes/OptionCategory.java
- donkoProject/src/main/java/controller/customer/CategoryServlet.java
- donkoProject/src/main/java/controller/customer/OptionServlet.java
- donkoProject/src/main/java/model/items/itemsSelect/SelectItemListFromItemsByOption.java
- donkoProject/src/main/webapp/WEB-INF/views/customer/categoryIndex.jsp
やっとこさ、カテゴリー毎のソートが完了しました。
重複した値を表示しないというのはこの後実装します
ブランチは消さないでください
> カテゴリー一覧のオプション選択do postの処理実装

- donkoProject/src/main/java/controller/customer/CartServlet.java
- donkoProject/src/main/java/controller/customer/PurchaseConfirmServlet.java
- donkoProject/src/main/java/model/purchaseDetails/purchaseDetailsInsert/InsertPurchaseDetail.java
- donkoProject/src/main/java/model/purchases/purchasesInsert/InsertPurchaseToPurchases.java
エクリプスに散々怒られてその通りに書いたやつです。
forEachの中のExceptionを外でキャッチできないかはもっと時間必要なのでお待ちを・・・（解決策見つけられないかもしれない）
> 購入時の処理のトランザクション化

- donkoProject/src/main/java/model/users/usersUpdate/UpdateUserInfoInUsers.java
更新するメソッドを作り忘れていました・・・
確認お願いします！
> ユーザー情報更新用のメソッド作成

- donkoProject/src/main/java/controller/customer/PurchaseConfirmServlet.java
> 合計金額算出の記述方法修正

- donkoProject/src/main/java/controller/customer/EditShippingAddressServlet.java
- donkoProject/src/main/webapp/WEB-INF/views/customer/shippingAddressEdit.jsp
一旦画面のみ作成しました。
配送先情報一覧は現在作成中なのでしばしお待ちください。
また、こちらも一旦画面表示のみの作成なので、それ以外の処理は後ほど作成します。
> 配送先情報編集画面作成

- donkoProject/src/main/java/controller/customer/CreateShippingAddressServlet.java
- donkoProject/src/main/webapp/WEB-INF/views/customer/shippingAddressCreate.jsp
一旦、画面だけ作成しています。
中の処理は後ほど対応しますので、いったん画面部分だけ確認お願いします！
> 配送先の登録画面作成

- donkoProject/src/main/java/bean/CartBean.java
- donkoProject/src/main/java/model/carts/cartsSelect/SelectItemListFromCarts.java
- donkoProject/src/main/webapp/WEB-INF/views/customer/cart.jsp
> 商品数量選択の上限設定

- donkoProject/src/main/java/controller/customer/ShippingAddressIndexServlet.java
- donkoProject/src/main/webapp/WEB-INF/views/customer/shippingAddressIndex.jsp
一旦、画面だけ作成しています。
サーブレットは後ほど作成していきます。
確認お願いします。
> 配送先一覧画面を作成

- donkoProject/src/main/java/classes/Item.java
- donkoProject/src/main/java/controller/admin/DeleteItemIndexServlet.java
- donkoProject/src/main/java/model/items/itemsSelect/SelectItemAndOptionListAll.java
- donkoProject/src/main/java/model/items/itemsSelect/SelectItemAndOptionListByDelFlg.java
・商品の一覧と付随するオプション
・削除済み⇔掲載中の商品の一覧と付随するオプション
削除商品一覧画面で必要になる情報だけをとってくる様なこーどにしたので、追加で欲しい情報があればSQLに追記してください。
全体でも、カテゴリー指定でもどちらでも値を取得できる様にしたけど、ややこしくなるので、とりあえずクラス名はそのままにしておきます。
> メソッド：商品一覧を取得

- donkoProject/src/main/webapp/WEB-INF/views/customer/home.jsp
> 画像横のマージンにaタグが反応していたので修正

- donkoProject/src/main/java/controller/customer/CartServlet.java
- donkoProject/src/main/java/controller/customer/ItemDetailServlet.java
- donkoProject/src/main/java/controller/customer/PurchaseConfirmServlet.java
- donkoProject/src/main/java/model/carts/cartsDelete/DeleteItemAllFromCarts.java
- donkoProject/src/main/java/model/carts/cartsDelete/DeleteItemFromCarts.java
- donkoProject/src/main/java/model/carts/cartsInsert/InsertItemToCarts.java
- donkoProject/src/main/java/model/carts/cartsSelect/SelectItemListFromCarts.java
- donkoProject/src/main/java/model/carts/cartsUpdate/UpdateItemQuantityInCarts.java
- donkoProject/src/main/java/model/items/itemsSelect/SelectItemDetailFromItems.java
- donkoProject/src/main/java/model/items/itemsSelect/SelectItemImageListFromItems.java
- donkoProject/src/main/java/model/purchases/purchasesInsert/InsertPurchaseToPurchases.java
- donkoProject/src/main/webapp/WEB-INF/views/customer/cart.jsp
- donkoProject/src/main/webapp/WEB-INF/views/customer/purchaseConfirm.jsp
> リファクタリング　コメント追加　定数名修正

- donkoProject/src/main/java/classes/OptionCategory.java
- donkoProject/src/main/java/controller/customer/CategoryServlet.java
- donkoProject/src/main/java/controller/customer/HomeServlet.java
- donkoProject/src/main/java/controller/customer/OptionServlet.java
- donkoProject/src/main/java/model/items/itemsSelect/SelectItemListFromItemsByOption.java
- donkoProject/src/main/webapp/WEB-INF/views/customer/categoryIndex.jsp
他の触っていたファイルの中も変数名を省略せずに表記したのと、命名規則に沿って名前を変更しました。
それとコメント追加しました。
> コードの変数名の変更

- donkoProject/src/main/java/classes/Item.java
- donkoProject/src/main/java/model/items/itemsSelect/SelectRandomItemListFromItems.java
これで担当箇所全ての実装が完了しました。
private static boolean isNotExist(ArrayList<ItemBean> Itemlist, String imageFileName) {}
はオプション選択した後の一覧表示でも使ってるので、共通化したいところではあります。
> ホーム画面の画像の重複なし＆メソッド名の変更

- donkoProject/src/main/java/controller/admin/AdminTopPageServlet.java
- donkoProject/src/main/java/controller/admin/PurchaseDetaiServlet.java
- donkoProject/src/main/java/controller/admin/PurchaseHistoryServlet.java
- donkoProject/src/main/webapp/WEB-INF/views/admin/adminTopPage.jsp
- donkoProject/src/main/webapp/WEB-INF/views/admin/purchaseDetail.jsp
- donkoProject/src/main/webapp/WEB-INF/views/admin/purchaseHistory.jsp
未発送一覧、受注詳細、受注一覧の３画面の見た目だけ作りました。
中身は明日やります。
> Adminホーム画面の作成

- donkoProject/src/main/java/controller/customer/OptionServlet.java
- donkoProject/src/main/java/model/items/itemsSelect/SelectItemListFromItemsByOption.java
- donkoProject/src/main/java/model/items/itemsSelect/SelectRandomItemListFromItems.java
- donkoProject/src/main/webapp/js/categoryIndexScript.js
とりあえず、foreachは今回の実装に適さないということが判明したので、
拡張for文で落ち着きました。
SQLはStringBilderに変更し、動作にも問題がないことを確認しています。
> リファクタリング by narumi

- donkoProject/src/main/java/classes/user/CustomerUser.java
- donkoProject/src/main/java/classes/user/User.java
セッションで実行できるように作成したので、元に戻しました。
確認お願いします。
戻せていないところがあれば教えてください。
> userクラスの修正

- donkoProject/src/main/java/model/shippingAddresses/shippingAddressesInsert/InsertNewShippingAddress.java
> 配送先メソッドの宛先追加

- donkoProject/src/main/java/bean/PurchaseBean.java
- donkoProject/src/main/java/controller/admin/PurchaseDetaiServlet.java
- donkoProject/src/main/java/model/purchases/purchasesSelect/SelectUnshippingItemListByDesc.java
> purchaseBeanのDateをTimestampに変更

- donkoProject/src/main/java/classes/user/User.java
- donkoProject/src/main/java/model/users/usersUpdate/UpdateUserPasswords.java
パスワードのメソッドを作成、既存のメソッドを修正しました。確認お願いします。
> パスワード関連の機能修正

- donkoProject/src/main/java/controller/user/EditUserInfoServlet.java
変数名を修正しきれていなかったので修正しました。
確認お願いします。
> ユーザー更新処理の変更漏れ

- donkoProject/src/main/java/bean/PurchaseBean.java
- donkoProject/src/main/java/controller/admin/AdminTopPageServlet.java
- donkoProject/src/main/java/model/purchases/purchasesSelect/SelectUnshippingItemListByDesc.java
- donkoProject/src/main/webapp/WEB-INF/views/admin/adminTopPage.jsp
未発送一覧の表示とそれぞれの項目のアノテーションをつけています。
購入詳細画面への遷移も成功しています。
ログアウトのボタンだけ未実装です。
> adminトップ画面の作成と表示完了

- donkoProject/src/main/java/controller/admin/DeleteItemIndexServlet.java
- donkoProject/src/main/java/model/items/itemsSelect/SelectItemAndOptionListAll.java
- donkoProject/src/main/java/model/items/itemsSelect/SelectItemAndOptionListByDelFlg.java
- donkoProject/src/main/webapp/WEB-INF/views/admin/deleteItemIndex.jsp
- donkoProject/src/main/webapp/css/deleteItemIndex.css
一覧表示と条件によるソートができる様になりました。
エラーハンドリングがおかしかったら指摘してちょう。
商品ステータスの切り替え方法はちょっと考え中です。
チェックボックスで複数一気に切り替えとかできたら良いよねぇ・・・
> Jsp 削除商品一覧

- donkoProject/src/main/java/model/purchases/purchasesSelect/SelectMyPurchaseHistory.java
> 購入履歴を取得するメソッドを修正

- donkoProject/src/main/webapp/WEB-INF/views/customer/myPage.jsp
画面遷移時のボタンとその他少しレイアウトを修正しました。確認お願いします。
> マイページレイアウト修正

- donkoProject/src/main/java/controller/customer/UserInfoEditServlet.java
- donkoProject/src/main/webapp/WEB-INF/views/customer/userInfoEdit.jsp
パスワードは別画面で表示させるため、画面から削除しました。確認お願いします。
> ユーザ情報編集画面修正

- donkoProject/src/main/java/controller/customer/MyPageServlet.java
セッションで実行できるように修正しました。
確認おねがいします。
> セッションで実行できるように修正

- donkoProject/src/main/java/controller/admin/AdminSigninServlet.java
- donkoProject/src/main/webapp/WEB-INF/views/admin/adminSignin.jsp
メソッドはまだ作ってません。
伊藤くんへ：AdminSigninServlet.javaにご相談を書いてます。
もう一つ、
model層でエラーが発生した時の遷移先ページを作成する場合、
SELECT文はreturn nullがあるから良いけど、
UPDATE,DELETE,INSERTはエラー吐いた時にどうしようかね？
chatchをサーブレットにthrowするか、戻り値をvoidじゃなくてbooleanにするか・・・
> アドミン側ログイン画面、jsp

- donkoProject/src/main/java/model/purchases/purchasesSelect/SelectMyPurchaseHistory.java
- donkoProject/src/main/java/model/shippingAddresses/shippingAddressesSelect/SelectShippingAddressDetail.java
- donkoProject/src/main/java/model/shippingAddresses/shippingAddressesSelect/SelectShippingAddressList.java
- donkoProject/src/main/java/model/shippingAddresses/shippingAddressesUpdate/UpdateMainShippingAddress.java
- donkoProject/src/main/java/model/shippingAddresses/shippingAddressesUpdate/UpdateShippingAddress.java
- donkoProject/src/main/java/model/users/usersUpdate/UpdateUserInfoInUsers.java
- donkoProject/src/main/java/model/users/usersUpdate/UpdateUserPasswords.java
> メソッドに記載しているSQLを修正

- donkoProject/src/main/java/controller/admin/SwichItemDelFlg.java
- donkoProject/src/main/webapp/WEB-INF/views/admin/deleteItemIndex.jsp
- donkoProject/src/main/webapp/js/deleteItemScript.js
ステータスをクリックすると文字が赤くなり、下の[チェックしたアイテムのステータスを切り替える]ボタンを押すと
削除済み⇔掲載中が切り替わります。
動作確認済みです。
本当は、submit時にアラートを表示するjsをつけたのですが、やはり動きません。
私はjsが嫌いになりそうです
これにて、削除商品一覧は一旦クローズして、ログイン画面に着手します。
> Jsp 商品削除切り替え

- donkoProject/src/main/java/classes/Item.java
- donkoProject/src/main/java/controller/admin/RegistItemServlet1.java
- donkoProject/src/main/java/controller/admin/RegistItemServlet2.java
- donkoProject/src/main/java/model/items/itemsInsert/InsertNewItemToItems.java
- donkoProject/src/main/webapp/WEB-INF/views/admin/registItem1.jsp
- donkoProject/src/main/webapp/WEB-INF/views/admin/registItem2.jsp
- donkoProject/src/main/webapp/js/registItemScript.js
商品新規登録周りのリファクタリング、コメントアウトを行いました。
・registItem1,2のサーブレット、jsp
新規登録について、一括登録機能を追加しました
・例）緑のS,M,Lサイズを一気に登録できる
一括登録と個別登録の機能表示をラジオボタンで切り替えて、
⭐️個別登録（緑のSサイズとか）→セレクトボックス
⭐️一括登録（緑のS,Mを一気に登録）→チェックボックス
が表示される様にしたのですが、jsファイルにスクリプトを書くとうまく動作せず、
jspに直書きしないと動きません。
誰かこの呪いを解いてください。
12/18 8:30
おはようございます。朝起きたら呪い解けてました。
jsファイルとjspを修正しています。
> 商品新規登録：機能追加

- donkoProject/src/main/java/classes/ShippingAddress.java
- donkoProject/src/main/java/model/shippingAddresses/shippingAddressesSelect/SelectMainShippingAddressSort.java
配送先一覧をメイン配送先順にソートして取得するメソッドを作成しました。
確認お願いします。
> 配送先一覧をメイン配送先順にソートして取得するメソッド

- donkoProject/src/main/java/classes/user/AdminUser.java
- donkoProject/src/main/java/controller/admin/AdminSigninServlet.java
- donkoProject/src/main/java/model/users/usersSelect/SelectAdminFromAdmins.java
- donkoProject/src/main/webapp/WEB-INF/views/admin/adminSignin.jsp
> セッション、メソッド追加

- donkoProject/src/main/java/controller/admin/RegistItemServlet1.java
SELECT文でトランザクションエラーが起きた場合の遷移先は、
状況に応じてsendRedirectとforwardを使い分けるということにしましょ💡
message.jspに遷移する時はerrorMessageが必要になるので、forwardになりますね。注意。
動作確認済みです。
> エラーハンドリングその１

- donkoProject/src/main/java/controller/admin/PurchaseHistoryServlet.java
- donkoProject/src/main/java/controller/customer/CategoryServlet.java
- donkoProject/src/main/java/model/purchases/purchasesSelect/SelectOrderItemList.java
- donkoProject/src/main/webapp/WEB-INF/views/admin/purchaseHistory.jsp
受注一覧の実装が完了しました。
少しばかりCSSも変更しました。
リファクタリングはまだです。
これで基本的な実装のみ終了です。
> Admin受注一覧の作成

- donkoProject/src/main/webapp/WEB-INF/views/admin/adminTopPage.jsp
> ユーザ側のホーム画面に遷移するボタンを追加

- donkoProject/src/main/java/controller/admin/AdminTopPageServlet.java
- donkoProject/src/main/java/controller/admin/PurchaseDetaiServlet.java
- donkoProject/src/main/java/controller/admin/PurchaseHistoryServlet.java
- donkoProject/src/main/java/model/purchases/purchasesSelect/SelectPurchaseInfo.java
> Admin側の各ファイルにコメント追加

- donkoProject/src/main/webapp/WEB-INF/views/customer/myPage.jsp
購入日の表示形式をyyyy-MM-dd hh:mm形式に変更
> 購入日の表示形式を修正

- donkoProject/src/main/webapp/WEB-INF/views/customer/userInfoEdit.jsp
actionのリンク先とbuttonタグを閉じれていなかったので修正
> マイページのJSPを修正

- donkoProject/src/main/java/controller/customer/UserInfoEditServlet.java
Userクラスのメソッドがstaticに変わったので、呼び出すコードを修正。
以前伊藤くんから修正依頼があったマイページへの遷移方法をリダイレクトで実行できるように修正。
> ユーザ情報編集サーブレットの修正

- donkoProject/src/main/webapp/WEB-INF/views/customer/userInfoEdit.jsp
title名がdokoになっていたので、donkoに修正しました。
確認お願いします。
> ユーザー情報編集JSPを修正

- donkoProject/src/main/java/classes/user/User.java
- donkoProject/src/main/java/controller/customer/UpdateUserPasswordServlet.java
- donkoProject/src/main/java/model/users/usersUpdate/UpdateUserPasswords.java
- donkoProject/src/main/webapp/WEB-INF/views/customer/userPasswordUpdate.jsp
パスワード変更画面を作成しました。
作成にあたり、一部メソッドも修正しています。
パスワード更新後は、現状ホーム画面に遷移するようにしていますが、ログイン画面に遷移する方がよければ教えてください。
> パスワード変更画面作成

- donkoProject/src/main/java/classes/Item.java
- donkoProject/src/main/java/classes/Option.java
- donkoProject/src/main/java/classes/OptionCategory.java
- donkoProject/src/main/java/controller/admin/RegistItemServlet1.java
- donkoProject/src/main/java/controller/admin/RegistItemServlet2.java
- donkoProject/src/main/java/model/items/itemsInsert/InsertNewItemToItems.java
- donkoProject/src/main/java/model/optionCategories/optionCategoriesSelect/SelectOptionCategoryListByCategory.java
画像を入れる場所のファイルパスを動的?に取得します。
商品登録側で動作確認済みです（商品編集側は未着手）
みのりさん・・・thank you・・・
関連するファイルは以下二つです。
[Item.java](https://github.com/ito-naoya/donkoProject/compare/%E3%82%B3%E3%83%B3%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%E3%83%91%E3%82%B9%E3%81%AE%E5%AF%BE%E5%BF%9C?expand=1#diff-43b6ab3efbb9982d603b04052adfdddfc193e4c929f62edfba11d59711f0329b)
[RegistItemServlet2.java](https://github.com/ito-naoya/donkoProject/compare/%E3%82%B3%E3%83%B3%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%E3%83%91%E3%82%B9%E3%81%AE%E5%AF%BE%E5%BF%9C?expand=1#diff-0e15b82f08c4606c8281c64353d6035031fd458a7fe3c1845103f85e6bbc1475)
> コンテキストパスの対応

- donkoProject/src/main/java/classes/Item.java
- donkoProject/src/main/java/classes/Option.java
- donkoProject/src/main/java/classes/OptionCategory.java
- donkoProject/src/main/java/controller/admin/RegistItemServlet1.java
- donkoProject/src/main/java/controller/admin/RegistItemServlet2.java
- donkoProject/src/main/java/model/items/itemsInsert/InsertNewItemToItems.java
- donkoProject/src/main/java/model/optionCategories/optionCategoriesSelect/SelectOptionCategoryListByCategory.java
おはよーござます🍺
商品登録周りのサーブレット、メソッドのエラーハンドリングを実施しました。
[bb043cb](https://github.com/ito-naoya/donkoProject/pull/164/commits/bb043cb71f121bac7007a20594fccb54de67e604)
メインは↑で、[3ad736c](https://github.com/ito-naoya/donkoProject/pull/164/commits/3ad736c75a52eaa59bfeb770628f4cafcc057201)
こっちは気にしないでください
> 新規登録画面：エラーハンドリング改

- donkoProject/src/main/java/classes/Item.java
- donkoProject/src/main/java/controller/admin/RegistItemServlet1.java
- donkoProject/src/main/java/controller/admin/RegistItemServlet2.java
- donkoProject/src/main/webapp/WEB-INF/views/admin/deleteItemIndex.jsp
- donkoProject/src/main/webapp/WEB-INF/views/admin/editItemInfo1.jsp
- donkoProject/src/main/webapp/WEB-INF/views/admin/editItemInfo2.jsp
- donkoProject/src/main/webapp/WEB-INF/views/admin/registItem1.jsp
- donkoProject/src/main/webapp/WEB-INF/views/admin/registItem2.jsp
> 新規登録画面：jspエラーハンドリング

- donkoProject/src/main/java/controller/admin/DeleteItemIndexServlet.java
> 商品一覧画面：サーブレット側エラーハンドリング

- donkoProject/src/main/java/classes/Cart.java
- donkoProject/src/main/java/classes/Purchase.java
- donkoProject/src/main/java/classes/user/AdminUser.java
- donkoProject/src/main/java/controller/admin/DeleteUserInfoServlet.java
- donkoProject/src/main/java/controller/admin/EditUserInfoServlet.java
- donkoProject/src/main/java/controller/customer/CartServlet.java
- donkoProject/src/main/java/controller/customer/DeleteCartServlet.java
- donkoProject/src/main/java/controller/customer/ItemDetailServlet.java
- donkoProject/src/main/java/controller/customer/PurchaseConfirmServlet.java
- donkoProject/src/main/java/model/carts/cartsDelete/DeleteItemAllFromCarts.java
- donkoProject/src/main/java/model/carts/cartsDelete/DeleteItemFromCarts.java
- donkoProject/src/main/java/model/carts/cartsInsert/InsertItemToCarts.java
- donkoProject/src/main/java/model/carts/cartsUpdate/UpdateItemQuantityInCarts.java
- donkoProject/src/main/java/model/purchases/purchasesInsert/InsertPurchaseToPurchases.java
- donkoProject/src/main/java/model/shippingAddresses/shippingAddressesSelect/SelectMainShippingAddress.java
- donkoProject/src/main/java/model/users/usersUpdate/UpdateUserInfoByAdmin.java
- donkoProject/src/main/webapp/WEB-INF/views/customer/cart.jsp
- donkoProject/src/main/webapp/WEB-INF/views/customer/purchaseConfirm.jsp
- donkoProject/src/main/webapp/css/cartStyle.css
- donkoProject/src/main/webapp/js/cartScript.js
INSERT UPDATE DELETE処理にreturn文追加してエラーページへの遷移も追加しましま。
確認お願いしましま。
（他のところも少し手を加えた）
> 商品詳細、カート、購入処理　エラーハンドリング

- donkoProject/src/main/java/controller/customer/MyPageServlet.java
- donkoProject/src/main/webapp/WEB-INF/views/customer/myPage.jsp
- donkoProject/src/main/webapp/js/myPageScript.js
１.タイトル名を購入IDから注文番号に変更
２.注文番号のフォントカラーを変更
３.tdの幅を修正
　縮小した時にスクロールできるようになっているので、ウィンドが縮小された時に文字が改行されないようにしてます。 ４.発送済みの非表示機能の追加
今回の発表ではこの機能は表示させる予定ではないので、
発表後にコメントアウトを消します。
（JSも作成済み）
５.マイページのサーブレットをリファクタリング
（リファクタリングはこれであっているのだろうか？？
認識が違っていたら教えてください。）
> マイページ画面の修正

- donkoProject/src/main/java/controller/admin/AdminTopPageServlet.java
- donkoProject/src/main/java/controller/admin/PurchaseDetaiServlet.java
- donkoProject/src/main/java/controller/admin/PurchaseHistoryServlet.java
- donkoProject/src/main/java/controller/admin/ShippingServlet.java
- donkoProject/src/main/java/controller/customer/CategoryServlet.java
- donkoProject/src/main/java/controller/customer/HomeServlet.java
- donkoProject/src/main/java/controller/customer/OptionServlet.java
- donkoProject/src/main/webapp/WEB-INF/views/admin/adminTopPage.jsp
- donkoProject/src/main/webapp/WEB-INF/views/admin/purchaseDetail.jsp
- donkoProject/src/main/webapp/WEB-INF/views/admin/purchaseHistory.jsp
- donkoProject/src/main/webapp/WEB-INF/views/customer/categoryIndex.jsp
- donkoProject/src/main/webapp/WEB-INF/views/customer/home.jsp
自分が触っていたファイルのsevletとjspのエラーハンドリングを完了しました。
基本的にifで囲ってるだけですが...
> コードの修正 by narumi

- donkoProject/src/main/java/controller/admin/DeleteItemIndexServlet.java
- donkoProject/src/main/webapp/WEB-INF/views/admin/deleteItemIndex.jsp
- donkoProject/src/main/webapp/WEB-INF/views/admin/editItemInfo1.jsp
- donkoProject/src/main/webapp/WEB-INF/views/admin/editItemInfo2.jsp
> 編集画面のサーブレットは後で直します

- donkoProject/src/main/java/controller/customer/MyPageServlet.java
- donkoProject/src/main/java/model/purchases/purchasesSelect/SelectMyPurchaseHistory.java
- donkoProject/src/main/webapp/WEB-INF/views/customer/myPage.jsp
- donkoProject/src/main/webapp/WEB-INF/views/customer/orderDetail.jsp
- donkoProject/src/main/webapp/WEB-INF/views/customer/shippingAddressIndex.jsp
１．サーブレットに記載していた、コミットを削除しました。
２．メイン配送先更新周りの修正
３．配送先一覧に郵便番号を追加
４．購入詳細画面を修正
　レイアウトと購入IDを注文IDに修正
　郵便番号と宛名を表示
５．マイページの郵便番号を追加
６．購入履歴のメソッドを修正
　　郵便番号と宛名を追加
（ エラーハンドリングはまた後で・・・）
> 購入履歴・購入詳細・配送先一覧修正

- donkoProject/src/main/java/bean/PurchaseBean.java
- donkoProject/src/main/java/controller/admin/PurchaseDetailServlet.java
- donkoProject/src/main/java/model/purchases/purchasesSelect/SelectPurchaseInfo.java
- donkoProject/src/main/webapp/WEB-INF/views/admin/adminTopPage.jsp
- donkoProject/src/main/webapp/WEB-INF/views/admin/purchaseDetail.jsp
- donkoProject/src/main/webapp/WEB-INF/views/admin/purchaseHistory.jsp
- donkoProject/src/main/webapp/WEB-INF/views/customer/categoryIndex.jsp
- donkoProject/src/main/webapp/WEB-INF/views/customer/home.jsp
まさかのSQLで取得した値をbeanにセットしてなかった。
初歩的なミス...
追記
また一個追加したので見てください
さらにまた一個追加したので見てください
さらにさらにまた一個追加しました
> 「発送する」ボタンの表示の切り替え完了

- donkoProject/src/main/java/controller/customer/ItemDetailServlet.java
- donkoProject/src/main/webapp/WEB-INF/views/customer/itemDetail.jsp
> 戻るボタンの遷移先の修正

- donkoProject/src/main/java/bean/PurchaseBean.java
> shippingAddress削除

- donkoProject/src/main/java/model/purchases/purchasesSelect/SelectPurchaseInfo.java
購入詳細画面で購入した時の宛名と郵便番号、住所が欲しかったので追加しました。確認お願いします。
> 購入情報のメソッドを修正

- donkoProject/src/main/webapp/WEB-INF/views/customer/editShippingAddress.jsp
- donkoProject/src/main/webapp/js/editShippingAddressScript.js
これを参考にバリデーションつけてください。
ひとまずブランチは消さないでください
[CSSの付け加え](https://github.com/ito-naoya/donkoProject/pull/194/commits/93aadf68e6ee0e3093ce00ae5e9cb98cb3bf7b3d)も見てね
> 配送先編集のバリデーション

- donkoProject/src/main/java/controller/customer/UserInfoIndexServlet.java
> ユーザー情報閲覧作成

- donkoProject/src/main/webapp/js/editShippingAddressScript.js
- donkoProject/src/main/webapp/js/userInfoEditScript.js
> バリデーションの変更

- donkoProject/src/main/java/controller/admin/RegistItemServlet2.java
- donkoProject/src/main/webapp/WEB-INF/views/admin/registItem2.jsp
- donkoProject/src/main/webapp/js/registItemScript.js
どうも、パレートの法則の2割になった女です。
商品登録時の不要なラジオボタンを削除しました。
> 不要なラジオボタン機能削除

- donkoProject/src/main/webapp/WEB-INF/views/customer/createShippingAddress.jsp
- donkoProject/src/main/webapp/WEB-INF/views/customer/editShippingAddress.jsp
- donkoProject/src/main/webapp/WEB-INF/views/customer/userInfoEdit.jsp
- donkoProject/src/main/webapp/js/nullValidationScript.js
- donkoProject/src/main/webapp/js/userInfoEditScript.js
donkoProject/src/main/webapp/js/nullValidationScript.js
を作ったので、formのバリデーションかけたい時はこれをjspで呼び出してください
> 新しくjsファイルを作りました

- donkoProject/src/main/java/controller/customer/MyPageServlet.java
マイページのエラーハンドリングしてみました。
エラーハンドリングはこんな感じでよろしいでしょうか？？
> マイページのエラーハンドリング

- donkoProject/src/main/webapp/WEB-INF/views/component/message.jsp
> Message.jsp追加

- donkoProject/src/main/java/classes/ShippingAddress.java
- donkoProject/src/main/java/controller/customer/CreateShippingAddressServlet.java
- donkoProject/src/main/java/model/shippingAddresses/shippingAddressesInsert/InsertNewShippingAddress.java
配送先のエラーハンドリングをしました。
また、関連するメソッドをBooleanに変更しました。
不具合がある場合は戻すので教えてください。
※doGetはエラーハンドリングしてないのですが、これで良いのでしょうか？？
※エラーハンドリングはどこまでしたら良いのかわからなくなってきた・・・
> 配送先登録のエラーハンドリング

- donkoProject/src/main/java/classes/user/User.java
- donkoProject/src/main/java/controller/customer/UserInfoEditServlet.java
- donkoProject/src/main/java/model/users/usersUpdate/UpdateUserInfoInUsers.java
1.ユーザ編集画面のエラーハンドリング
2.エラーハンドリングに伴う、メソッドを修正
　voidからbooleanに変更
勝手に変えてしまったので、もし不都合や不要な修正であれば指摘ください。
> ユーザ編集のエラーハンドリング

- donkoProject/src/main/webapp/WEB-INF/views/customer/myPage.jsp
> マイページのJSPをエラーハンドリング

- donkoProject/src/main/java/classes/BeanValidation.java
- donkoProject/src/main/java/classes/user/CustomerUser.java
- donkoProject/src/main/java/controller/admin/EditUserInfoServlet.java
- donkoProject/src/main/webapp/WEB-INF/views/admin/editUserInfo.jsp
validation再度改良しました。
ユーザー編集の時パスワード入力しないから一生アノテーション引っかかる問題はなんとかしないとですね・・・
beanでクラス継承とか考えてますけど、今日は疲れたかもしれない🐶🐶🐶🐶🐶🐶🐶
bootstrapのnullチェックとの併用もちょっと工夫が必要そうで最悪bootstrapなしになるかも
メソッドもどこまで共通化するかって感じですけど、とりあえずの範囲でしました
> Bean validation実装

- donkoProject/src/main/java/classes/BeanValidation.java
- donkoProject/src/main/java/classes/user/CustomerUser.java
> バリデーション　修正

- donkoProject/src/main/java/classes/BeanValidation.java
- donkoProject/src/main/java/classes/user/CustomerUser.java
- donkoProject/src/main/java/controller/admin/EditUserInfoServlet.java
- donkoProject/src/main/java/controller/customer/CartServlet.java
- donkoProject/src/main/java/interfaces/group/GroupA.java
- donkoProject/src/main/java/interfaces/group/GroupB.java
- donkoProject/src/main/java/interfaces/group/GroupC.java
- donkoProject/src/main/webapp/WEB-INF/views/admin/editUserInfo.jsp
グループ化できました。
パスワードがアノテーションに引っ掛からないのはインプットフォームがなくて空文字すら渡されないからチェックされてないように見えました。
直接セッターでセットしたらちゃんとエラー吐いたので大丈夫かと
> アノテーションのグループ化

- donkoProject/src/main/java/classes/ShippingAddress.java
- donkoProject/src/main/java/controller/customer/ShippingAddressIndexServlet.java
- donkoProject/src/main/java/model/shippingAddresses/shippingAddressesUpdate/UpdateMainShippingAddress.java
- donkoProject/src/main/webapp/WEB-INF/views/customer/shippingAddressIndex.jsp
バイテーション以外をエラーハンドリングしました。
抜け漏れ、間違いがあれば指摘お願いします。
> 配送先一覧のエラーハンドリング

- donkoProject/src/main/java/controller/customer/UserInfoEditServlet.java
確認お願いします。
頭がパンク寸前なのでバリテーションチェックは後回しで許してください。。。。
それ以外のエラーハンドリングを優先的にしていきます。。
土日でなんとかします
> ユーザ編集画面のエラーハンドリング

- donkoProject/src/main/java/controller/customer/CreateShippingAddressServlet.java
戻るボタンの部分の文言を追加
バリテーションは後ほどで・・・・
> 配送先登録画面の修正

- donkoProject/src/main/java/classes/Item.java
- donkoProject/src/main/java/controller/admin/RegistItemServlet1.java
- donkoProject/src/main/java/controller/admin/RegistItemServlet2.java
- donkoProject/src/main/java/model/items/itemsInsert/InsertNewItemToItems.java
- donkoProject/src/main/java/model/items/itemsSelect/SelectItemAlreadyExistFromItems.java
- donkoProject/src/main/webapp/WEB-INF/views/admin/registItem1.jsp
商品編集側の重複はこれから着手。
Beans Validationもこれから着手。
> 商品登録時の重複を排除

- donkoProject/src/main/java/classes/ErrorHandling.java
- donkoProject/src/main/java/controller/admin/AdminTopPageServlet.java
- donkoProject/src/main/java/controller/admin/DeleteItemIndexServlet.java
- donkoProject/src/main/java/controller/admin/DeleteUserInfoServlet.java
- donkoProject/src/main/java/controller/admin/EditItemInfo1Servlet.java
- donkoProject/src/main/java/controller/admin/EditItemInfo2Servlet.java
- donkoProject/src/main/java/controller/admin/EditUserInfoServlet.java
- donkoProject/src/main/java/controller/admin/PurchaseDetailServlet.java
- donkoProject/src/main/java/controller/admin/RegistItemServlet1.java
- donkoProject/src/main/java/controller/admin/RegistItemServlet2.java
- donkoProject/src/main/java/controller/admin/ShippingServlet.java
- donkoProject/src/main/java/controller/customer/CartServlet.java
- donkoProject/src/main/java/controller/customer/DeleteCartServlet.java
- donkoProject/src/main/java/controller/customer/DeleteFlagUserServlet.java
- donkoProject/src/main/java/controller/customer/HomeServlet.java
- donkoProject/src/main/java/controller/customer/MyPageServlet.java
- donkoProject/src/main/java/controller/customer/PurchaseConfirmServlet.java
- donkoProject/src/main/java/controller/customer/ShippingAddressIndexServlet.java
- donkoProject/src/main/java/controller/customer/UserInfoEditServlet.java
- donkoProject/src/main/java/controller/customer/UserInfoPageServlet.java
メソッド共通化して既存コードの書き換えだけしました。
確認お願いします
> エラーハンドリング　メソッド共通化

- donkoProject/src/main/webapp/WEB-INF/views/customer/myPage.jsp
- donkoProject/src/main/webapp/js/myPageScript.js
> 発送ステータスの切替え修正

- donkoProject/src/main/java/bean/ShippingAddressBean.java
- donkoProject/src/main/java/controller/customer/EditShippingAddressServlet.java
配送先登録のバリテーションチェックしました。
先ほど伊藤くんに教えてもらったものが反映できていなかったです。。
> 配送先登録のバリテーションチェック

- donkoProject/src/main/webapp/WEB-INF/views/customer/myPage.jsp
> 購入履歴のフォーマットを修正

- donkoProject/src/main/java/model/carts/cartsInsert/InsertItemToCarts.java
カートに入れるボタンからの在庫無視無限追加のバグ直しました。
> カートに入れる機能の修正

- donkoProject/src/main/java/controller/customer/EditShippingAddressServlet.java
- donkoProject/src/main/webapp/WEB-INF/views/customer/editShippingAddress.jsp
> 配送先編集のバリテーション修正

- donkoProject/src/main/java/classes/user/User.java
- donkoProject/src/main/java/controller/customer/UserInfoEditServlet.java
- donkoProject/src/main/java/model/users/usersUpdate/UpdateUserInfoInUsers.java
- donkoProject/src/main/webapp/WEB-INF/views/customer/userInfoEdit.jsp
ユーザ情報編集画面のバリテーションチェックとエラーハンドリング済みです。
確認お願いします、
> ユーザ情報編集画面のバリテーションチェック

- donkoProject/src/main/java/controller/customer/ShippingAddressIndexServlet.java
- donkoProject/src/main/java/model/shippingAddresses/shippingAddressesUpdate/UpdateMainShippingAddress.java
- donkoProject/src/main/webapp/WEB-INF/views/customer/shippingAddressIndex.jsp
> 配送先一覧のバリテーションチェック修正

- donkoProject/src/main/webapp/WEB-INF/views/customer/myPage.jsp
合計金額がウィンドウをスクショーさせると折れてしまっていたので、修正しました。
確認よろ・
> 購入履歴の表示を修正

- donkoProject/src/main/java/controller/customer/DeleteShippingAddressServlet.java
> 配送先削除機能のリファクタ

- donkoProject/src/main/java/classes/user/CustomerUser.java
- donkoProject/src/main/java/classes/user/User.java
- donkoProject/src/main/java/controller/admin/RegistItemServlet2.java
- donkoProject/src/main/java/controller/user/UserSignupServlet.java
- donkoProject/src/main/java/model/users/usersInsert/InsertNewUserToUsers.java
- donkoProject/src/main/java/model/users/usersSelect/SelectUserDuplicate.java
- donkoProject/src/main/webapp/WEB-INF/views/user/userSignup.jsp
inputboxの初期値がnullになるのは後で直すとして・・・
とりあえずユーザー新規登録関係は完了しました。
なにこのライブラリめっちゃ面白いーーーーー！！！
なおぴありがとうね！！
塩川組ばりのセキュリティは入れないにしても、
パスワードは２回書かせる位の事はしようかねぇ・・・w
> 新規登録画面バリデーション動作確認

- donkoProject/src/main/java/controller/customer/CartServlet.java
- donkoProject/src/main/java/controller/customer/DeleteCartServlet.java
- donkoProject/src/main/java/controller/customer/ItemDetailServlet.java
- donkoProject/src/main/java/controller/customer/PurchaseConfirmServlet.java
ログインありきのやつなのでログインと一緒にマージお願いします
> ページのアクセス制限の実装

- donkoProject/src/main/java/controller/customer/UpdateUserPasswordServlet.java
- donkoProject/src/main/webapp/WEB-INF/views/customer/sampleUserSignin.jsp
- donkoProject/src/main/webapp/WEB-INF/views/customer/userPasswordUpdate.jsp
バリテーションチェック追加
伊藤くんがログイン画面を作成してくれたのでリンクを追加しました。
確認よろよろ
> パスワード変更機能関連

- donkoProject/src/main/java/controller/customer/MyPageServlet.java
伊藤くんがログイン画面を作成してくれたので、テストコードを削除しました。
> セッション追加によるテストコード削除

- donkoProject/src/main/java/bean/ShippingAddressBean.java
- donkoProject/src/main/java/classes/ShippingAddress.java
- donkoProject/src/main/java/controller/customer/CreateShippingAddressServlet.java
- donkoProject/src/main/java/model/shippingAddresses/shippingAddressesSelect/SelectMainShippingAddressCount.java
配送先を登録していない状態で、配送先登録を実行するとエラー画面に遷移されるのでメソッドを追加しました。
> 配送先が登録されていない時の修正

- donkoProject/src/main/java/model/carts/cartsInsert/InsertItemToCarts.java
> カート追加機能　修正

- donkoProject/.classpath
- donkoProject/src/main/java/test/model/items/itemsSelect/TestSelectItemDetailFromItems.java
- donkoProject/src/main/java/test/model/items/itemsSelect/TestSelectItemImageListFromItems.java
２個だけテストケース実装しました。
JUnit追加されてるので、マージしてフェッチした時に入るかと
> テストケース　商品詳細

- donkoProject/src/main/java/model/purchases/purchasesSelect/SelectPurchaseInfo.java
- donkoProject/src/main/webapp/WEB-INF/views/customer/myPage.jsp
- donkoProject/src/main/webapp/WEB-INF/views/customer/shippingAddressIndex.jsp
> 郵便番号の表示を修正

- donkoProject/src/main/java/bean/ShippingAddressBean.java
- donkoProject/src/main/java/classes/ShippingAddress.java
- donkoProject/src/main/java/controller/customer/CreateShippingAddressServlet.java
- donkoProject/src/main/java/model/shippingAddresses/shippingAddressesSelect/SelectMainShippingAddressCount.java
メイン配送先の登録にて、追加で作成しても、メイン配送先として登録されてしまっていたので修正しました。
また、不要なコードも削除しています。
> メイン配送先の設定を修正

- donkoProject/src/main/webapp/WEB-INF/views/customer/myPage.jsp
- donkoProject/src/main/webapp/js/createShippingAddress.js
配送先登録のバリテーションをJSで作成しました。
確認お願いします。
※文字のレイアウト変更は後はテストケースが終わってから対応します。
※TO:なるちゃん
配送先編集もモーダルウィンドに変更しても問題ないです！
> 配送先登録のバリテーション作成

- donkoProject/src/main/java/controller/customer/UserInfoEditServlet.java
Dateがエラーになっていたので空文字できた時の処理を記載しました。
伊藤くんありがとう！
> ユーザー情報編集画面修正

- donkoProject/src/main/java/classes/user/User.java
- donkoProject/src/main/java/controller/user/LogoutServlet.java
admin側とユーザ側でログアウト後の遷移先を変更
追記：
管理者側のエラー時の画面遷移先指定してないや・・・
どこに遷移すべきなんだろう？
> ログアウト機能の修正

- donkoProject/src/main/java/controller/admin/EditUserInfoServlet.java
- donkoProject/src/main/webapp/WEB-INF/views/admin/editUserInfo.jsp
> 誕生日と性別の選択肢修正

- donkoProject/src/main/webapp/WEB-INF/views/customer/myPage.jsp
エラーメッセージを表示させるときのレイアウトを修正し忘れていたので修正しました。
> 配送先登録のエラーメッセージ部分のCSS修正

- donkoProject/src/main/java/controller/customer/MyPageServlet.java
- donkoProject/src/main/java/controller/customer/ShippingAddressIndexServlet.java
なるちゃんが追加してくれたヘッダー部分の機能をユーザ側の機能に追加しました。
> 各機能のヘッダー表示部分を追加

- donkoProject/src/main/webapp/WEB-INF/views/customer/userSignin.jsp
ログイン画面：jspファイルの修正を行ったので、確認と問題なければマージもお願いします。
> ログインページのjsp修正

- donkoProject/src/main/java/test/classes/TestOption.java
> classes.option関係テスト

- donkoProject/src/main/java/controller/customer/UserInfoEditServlet.java
- donkoProject/src/main/webapp/WEB-INF/views/customer/myPage.jsp
性別がNullの場合になぜか「選択してください」が表示されるので、回避処理を入れていたのですが、DBに「選択してください」が入ってしまっていたので、nullで入るように修正しました。
> ユーザー編集画面の修正

- donkoProject/src/main/webapp/WEB-INF/views/customer/sampleUserSignin.jsp
- donkoProject/src/main/webapp/js/customerUserSigninScript.js
ユーザーのログイン画面のパスワード欄によくいるあいつ（目のやつ）を追加しました。
> パスワード表示切り替え

- donkoProject/src/main/java/controller/admin/EditUserInfoServlet.java
アドミン側の性別の値の格納をみのりさんの方に合わせました
選択してくださいの場合はNULLを保存
> 保存する値の条件追加

- donkoProject/src/main/webapp/WEB-INF/views/customer/editShippingAddress.jsp
- donkoProject/src/main/webapp/js/editShippingAddress.js
CSSの変更とエラー表示の修正を行いました。
確認よろしくです。
> 配送先編集のエラーメッセージcss変更

- donkoProject/src/main/java/model/items/itemsSelect/SelectItemOptionListFromItems.java
- donkoProject/src/main/java/model/shippingAddresses/shippingAddressesSelect/SelectMainShippingAddress.java
- donkoProject/src/main/java/model/users/usersUpdate/UpdateUserInfoByAdmin.java
- donkoProject/src/main/java/test/model/carts/cartsSelect/TestSelectItemListFromCarts.java
- donkoProject/src/main/java/test/model/items/itemsSelect/TestSelectItemDetailFromItems.java
- donkoProject/src/main/java/test/model/items/itemsSelect/TestSelectItemOptionListFromItems.java
- donkoProject/src/main/java/test/model/purchases/purchasesInsert/TestInsertPurchaseToPurchases.java
- donkoProject/src/main/java/test/model/shippingAddress/shippingAddressesSelect/TestSelectMainShippingAddress.java
- donkoProject/src/main/java/test/model/users/usersUpdate/TestUpdateUserInfoByAdmin.java
自分が担当した範囲のテストケースは実装完了したと思います。
いくつか自分が実装したこと忘れてリファクタリングかけてなかったところあるんで確認しておきます。
> 商品詳細　カート　購入処理　テストケース

- donkoProject/src/main/java/model/itemCategories/itemCategoriesSelect/SelectOptionCategoryNameListByCategory.java
- donkoProject/src/main/java/model/items/itemsInsert/InsertNewItemToItems.java
- donkoProject/src/main/java/model/items/itemsUpdate/UpdateItemInfoInItems.java
- donkoProject/src/main/java/model/optionCategories/optionCategoriesSelect/SelectOptionCategoryListByCategory.java
- donkoProject/src/main/java/test/model/itemCategories/itemCategoriesSelect/TestSelectOptionCategoryNameListByCategory.java
- donkoProject/src/main/java/test/model/itemCategories/itemCategoriesSelect/TestselectItemCategoryList.java
- donkoProject/src/main/java/test/model/items/itemsInsert/TestInsertNewItemToItems.java
- donkoProject/src/main/java/test/model/items/itemsSelect/TestSelectItemAlreadyExistFromItems.java
- donkoProject/src/main/java/test/model/items/itemsSelect/TestselectItemCategoryList.java
- donkoProject/src/main/java/test/model/items/itemsUpdate/TestUpdateItemInfoInItems.java
- donkoProject/src/main/java/test/model/optionCategories/optionCategoriesSelect/TestSelectOptionCategoryListByCategory.java
> 商品登録、編集系メソッドテストケース

- donkoProject/src/main/java/model/items/itemsSelect/SelectItemAllDetailFromItems.java
- donkoProject/src/main/java/model/items/itemsSelect/SelectItemAndOptionListAll.java
- donkoProject/src/main/java/model/items/itemsSelect/SelectItemAndOptionListByDelFlg.java
- donkoProject/src/main/java/model/items/itemsSelect/SelectItemNameListFromItemsByCategory.java
- donkoProject/src/main/java/model/users/usersInsert/InsertNewUserToUsers.java
- donkoProject/src/main/java/test/model/items/itemsInsert/TestInsertNewItemToItems.java
- donkoProject/src/main/java/test/model/items/itemsSelect/TestSelectItemAllDetailFromItems.java
- donkoProject/src/main/java/test/model/items/itemsSelect/TestsSlectItemAndOptionListByDelFlg.java
- donkoProject/src/main/java/test/model/items/itemsSelect/TestselectItemAndOptionListAll.java
- donkoProject/src/main/java/test/model/items/itemsSelect/TestselectItemNameListFromItemsByCategory.java
- donkoProject/src/main/java/test/model/users/usersInsert/TestInsertNewUserToUsers.java
- donkoProject/src/main/java/test/model/users/usersSelect/TestSelectAdminFromAdmins.java
> 商品編集、並び替え周りテストケース

- donkoProject/src/main/java/classes/user/CustomerUser.java
- donkoProject/src/main/java/controller/user/UserSignupServlet.java
- donkoProject/src/main/webapp/WEB-INF/views/user/userSignup.jsp
- donkoProject/src/main/webapp/js/userSignup.js
伊藤くんの目隠しを拝借したのと
パスワードに正規表現を追加。数字と文字を1つ以上含む様に変更しました。
29日に改めてLINEで周知します！
> 新規登録バリデーション追加

- donkoProject/src/main/java/bean/ShippingAddressBean.java
- donkoProject/src/main/java/test/classes/user/TestUser.java
- donkoProject/src/main/webapp/WEB-INF/views/customer/editShippingAddress.jsp
- donkoProject/src/main/webapp/WEB-INF/views/customer/myPage.jsp
- donkoProject/src/main/webapp/WEB-INF/views/customer/userPasswordUpdate.jsp
- donkoProject/src/main/webapp/js/myPageScript.js
> パスワード変更のレイアウト変更

- donkoProject/src/main/java/test/model/users/usersUpdate/TestUpdateUserInfoUsers.java
成功ケースのみ実施。
失敗ケースはuserIdがint型なので、対応方法を検討し後ほど対応予定。
> ユーザ情報更新テスト

- donkoProject/src/main/java/test/model/users/usersUpdate/TestUpdateUserPasswords.java
成功ケースは実施済み
失敗ケースはハッシュ化でエラーが吐いたので、一旦保留
> パスワード更新テスト

- donkoProject/src/main/java/test/model/purchases/purchasesSelect/TestSelectMyPurchaseHistory.java
> ユーザ購入履歴取得テスト

- donkoProject/src/main/java/test/model/users/usersUpdate/TestUpdateUserDeleteFlag.java
> ユーザ論理削除テスト

- donkoProject/src/main/webapp/WEB-INF/views/customer/shippingAddressIndex.jsp
> 配送先削除確認画面追加

- donkoProject/src/main/webapp/WEB-INF/views/customer/myPage.jsp
- donkoProject/src/main/webapp/js/myPageScript.js
> 退会時の確認画面を追加

- donkoProject/src/main/java/model/purchases/purchasesSelect/SelectOrderItemList.java
以前修正したはずなのに反映されていなかったので修正しました。
purchasesテーブルにあった
shipping_address_idを廃止したので、メソッドを修正してます。
> 受注一覧のメソッド修正

- donkoProject/src/main/java/controller/customer/CreateShippingAddressServlet.java
- donkoProject/src/main/java/controller/customer/EditShippingAddressServlet.java
- donkoProject/src/main/webapp/WEB-INF/views/customer/myPage.jsp
- donkoProject/src/main/webapp/js/createShippingAddress.js
正規表現で全角の数字書きたときに、半角数値に変換する処理を追加。
> 郵便番号の置換処理追加

- donkoProject/src/main/java/model/shippingAddresses/shippingAddressesUpdate/UpdateShippingAddress.java
- donkoProject/src/main/java/test/model/shippingAddress/shippingAddressesUpdate/TestUpdateShippingAddress.java
> 配送先情報更新メソッド修正とテスト

- donkoProject/src/main/java/test/model/shippingAddress/shippingAddressesDelete/TestDeleteShippingAddresses.java
- donkoProject/src/main/java/test/model/shippingAddress/shippingAddressesUpdate/TestUpdateMainShippingAddress.java
> メイン配送先更新テスト

- donkoProject/src/main/java/test/model/users/usersSelect/TestUserDetailFromUsers.java
> ユーザ詳細情報テスト

- donkoProject/src/main/java/model/shippingAddresses/shippingAddressesSelect/SelectMainShippingAddressSort.java
> 配送先のソートメソッドを修正

- donkoProject/src/main/webapp/WEB-INF/views/customer/orderDetail.jsp
購入詳細画面の郵便番号の表示形式を修正し忘れていたので修正しました。
> 購入詳細画面の郵便番号の表示修正

- donkoProject/src/main/java/controller/customer/OrderDetailServlet.java
購入詳細画面にヘッダーの処理を追加していなかったので追加しました。
> 購入詳細画面のカート数量修正

- donkoProject/src/main/java/model/items/itemsSelect/SelectItemListFromItemsByCategory.java
- donkoProject/src/main/java/model/purchases/purchasesSelect/SelectOrderItemList.java
- donkoProject/src/main/java/model/purchases/purchasesUpdate/UpdateShippingStatus.java
- donkoProject/src/main/java/test/classes/TestOptionCategory.java
- donkoProject/src/main/java/test/model/items/itemsSelect/TestSelectItemListFromItemsByCategory.java
- donkoProject/src/main/java/test/model/items/itemsSelect/TestSelectItemListFromItemsByOption.java
- donkoProject/src/main/java/test/model/items/itemsSelect/TestSelectRandomItemListFromItems.java
- donkoProject/src/main/java/test/model/purchases/purchasesSelect/TestSelectOrderItemList.java
- donkoProject/src/main/java/test/model/purchases/purchasesSelect/TestSelectPurchaseInfo.java
- donkoProject/src/main/java/test/model/purchases/purchasesSelect/TestSelectUnshippingItemListByDesc.java
- donkoProject/src/main/java/test/model/purchases/purchasesUpdate/TestUpdateShippingStatus.java
ほぼ皆さんのやってること見て真似た部分ばかりです。
ちょっと楽してしまった感。
引数なしのSQL文があるところは、エラー吐かせる方法がなかったので、テストとしてはエラーになってます。
ただまあ一応コードを残してはいる。
> 担当箇所のテストケースの完了

- donkoProject/src/main/webapp/WEB-INF/views/customer/userPasswordUpdate.jsp
- donkoProject/src/main/webapp/js/updatePassword.js
> パスワード変更の修正

- donkoProject/src/main/webapp/WEB-INF/views/customer/myPage.jsp
> マイページ画面を修正

- donkoProject/src/main/java/controller/user/UserSignupServlet.java
ユーザー側から入った時の遷移先を
ログイン画面になおしました
> 新規登録の遷移先変更

- donkoProject/src/main/java/test/model/itemCategories/itemCategoriesInsert/TestInsertItemCategories.java
- donkoProject/src/main/java/test/model/optionCategories/optionCategoriesSelect/TestSelectOptionCategoryList.java
- donkoProject/src/main/java/test/model/options/optionsDelete/TestDeleteItemOptionName.java
- donkoProject/src/main/java/test/model/options/optionsInsert/TestInsertItemOptionName.java
- donkoProject/src/main/java/test/model/options/optionsInsert/TestInsertItemOptionValue.java
> オプション/カテゴリテストケース

- donkoProject/src/main/java/controller/user/SampleUserSigninServlet.java
- donkoProject/src/main/java/model/users/usersSelect/SampleSelectUserFromUsers.java
入力ミスの時
アカウントが無効の時
上記２つでの表示するエラーメッセージの変更
> ログイン時のエラーメッセージの修正

- donkoProject/src/main/webapp/WEB-INF/views/admin/adminTopPage.jsp
- donkoProject/src/main/webapp/WEB-INF/views/component/footer.jsp
- donkoProject/src/main/webapp/WEB-INF/views/customer/categoryIndex.jsp
- donkoProject/src/main/webapp/WEB-INF/views/customer/myPage.jsp
- donkoProject/src/main/webapp/WEB-INF/views/customer/purchaseComplete.jsp
- donkoProject/src/main/webapp/WEB-INF/views/customer/userPasswordUpdate.jsp
> アドミン側のcssの変更

- donkoProject/src/main/java/controller/customer/DeleteAccountServlet.java
- donkoProject/src/main/webapp/WEB-INF/views/component/header.jsp
- donkoProject/src/main/webapp/WEB-INF/views/customer/deleteAccount.jsp
- donkoProject/src/main/webapp/WEB-INF/views/customer/myPage.jsp
- donkoProject/src/main/webapp/WEB-INF/views/customer/purchaseComplete.jsp
- donkoProject/src/main/webapp/WEB-INF/views/customer/shippingAddressIndex.jsp
> ユーザー側のcssの変更

- donkoProject/src/main/webapp/WEB-INF/views/customer/myPage.jsp
> placeholderを削除

- donkoProject/src/main/webapp/WEB-INF/views/customer/myPage.jsp
- donkoProject/src/main/webapp/js/myPageScript.js
JSが動かなくなったので修正。
一部パターンの時は想定外の挙動のため、修正予定。
JSPはフォーマットを整形しただけ。
> 配送先一覧の表示切り替え修正
